### ISSUE TITLE
Calling via action URL doesn't work

### ISSUE THREAD

**Issue by russback** [engram-design/FeedMe#12]
Hi

We can pull feeds fine on demand but the task URL that we are calling via Cron just doesn't run. For example:

http://domain.com/actions/feedMe/feeds/runTask?direct=1&feedId=1&passkey=MYPASSKEY

The result we get indicates that it should have been successful, but the the task isn't listed in the Logs tab so it appears it hasn't run:

    {
        success: "Feed ID: 1 - Task started"
    }

**Comment by engram-design** [comment]
@russback Please ignore the Logs tab, as that will be shortly removed until further notice, as its not being used. Database logging was removed a few versions ago due to performance issues. Instead, all logging is done to the file system. Is the feed actually not updating entries, or are you just suspecting its not due to nothing showing in the Logs tab?

**Comment by russback** [comment]
@engram-design which file do you log to? I've checked /mgmt/utils/logs but can't see any plugin-specific logs there.

**Comment by engram-design** [comment]
@russback After having a look at the log process, there was missing output for when an entry was successfully updated/added. So if you're not seeing a log file in there - thats possibly good now.

In any case, if you could try out the latest version (1.2.8) which fixes this, and see what the log file contains. It will just be called `feedme.log`, and yes, you can access it through /mgmt/utils/logs.

**Comment by russback** [comment]
@engram-design thanks, we're on `1.3.0` now but no `feedme.log` exists in the log directory and therefore not showing in `mgmt/utils/logs`.

We're seeing tasks stuck in the task queue and no entries being created. This is across 4 different feeds, for example:

````
{"id":"286","level":"0","description":"Food Manufacture","status":"running","progress":1
````

Where to go from here without logs to help?

**Comment by engram-design** [comment]
@russback Hmm - Would you be able to use the [support widget](https://github.com/engram-design/FeedMe#support) for one of those sites? It'll package up all the necessary files so I can investigate further.

**Comment by russback** [comment]
What do you need? Be quicker if I send direct to you and give you CMS access

**Comment by engram-design** [comment]
Okay, but there is a lot that it gathers such as your feed settings (mapping and general), fields used for mapping, log files, and your feed itself.

Otherwise, are you on the Craft Slack? Feel free to DM me and we can chat further. I can't look at it right now, but could certainly look at it in the next 24 hours.

**Comment by russback** [comment]
I've asked for an invite but it's not come through. Will drop Brad an email.

In the mean time, either that support plugin or a tar of the site and db?

**Comment by engram-design** [comment]
Ah, sure thing. Yeah, just use the Help tab in Feed Me, no need to zip up your entire site. Feel free to drop me an email directly via web@sgroup.com.au as well.

**Comment by russback** [comment]
Sent via Help tab. Will email you at web@sgroup.com.au now so we're not cluttering this issue thread. Thanks

**Comment by russback** [comment]
What's your username on Slack?
