### ISSUE TITLE
Ability to import multiple (related) products at once 

### ISSUE THREAD

**Issue by ax2000** [engram-design/FeedMe#1432]
### Description
I am trying to import Commerce Product element types that have a "Commerce Products" field that provides a "Related Products" functionality for each product. 
![Screenshot 2024-04-19 at 12 26 30](https://github.com/craftcms/feed-me/assets/2585959/16da3eaa-c386-4616-a80a-7040052e7aa2)

It seems that the Related Commerce Product field only accepts a string at the moment and, when providing an array of product Ids, I'm getting the error `trim(): Argument #1 ($string) must be of type string, array given - CommerceProducts.php: 110`.
![Screenshot 2024-04-19 at 12 27 10](https://github.com/craftcms/feed-me/assets/2585959/42e2bdd6-c4d4-44e3-b1cf-4b955b9e8b0e)

Would it be possible that the Commerce Product entry types accept an array similar to what Entries, Assets and Categories field do so it can import multiple related products for each product? 

I might be missing something though, so feel free to point me in the right direction if that's the case.

Thanks heaps!

### Additional info

- Craft version: 4.8.9
- PHP version: 8.2.10
- Database driver & version: MySQL 8.0.33
- Plugins & versions: 5.4.0

**Comment by i-just** [comment]
Hi, thanks for reaching out! Could you please share a snippet of your feed that causes this error to be thrown?

**Comment by ax2000** [comment]
Thanks for looking into this.

The feed looks like:
```
      ....
      "related_products": [],
      "crossell_products": [
        5272,
        5306
      ],
      ....
```
<img width="795" alt="Screenshot 2024-05-03 at 10 25 42" src="https://github.com/craftcms/feed-me/assets/2585959/08ac81d0-0fd0-43ae-b9cf-7fc7c658b52b">

The values in the crossell_products array above are product entry ids. And the feed is set to match by entry id as per:
<img width="887" alt="Screenshot 2024-05-03 at 10 28 50" src="https://github.com/craftcms/feed-me/assets/2585959/28f3abf1-2641-41a2-a45a-cf60976b5a63">

Please let me know if you'd need me to provide anything else.

**Comment by i-just** [comment]
Thanks, that helped!

You can already import multiple related products at once. That’s true for any field that extends `BaseRelationField`, such as Commerce Products, Assets, Entries, etc.

So `related_products` in your feed is an empty array, your feed maps `relatedProducts` to `related_products`, and you have “Default Product” selected too - is that correct?

I have raised a PR to improve this, but for now, if you change your feed to use `null` instead of an empty array for the `related_products` (and any other relational fields that are not supposed to have a value), it should work as expected.

**Comment by ax2000** [comment]
Thanks for your response @i-just.

You are right, I was overlooking the way it was suppose to accept the feed data.

It is all working correctly now!
