### ISSUE TITLE
Default asset value is not used for an asset field when no asset URL is defined or provided.

### ISSUE THREAD

**Issue by jamesmacwhite** [engram-design/FeedMe#1493]
### Description

I don't know if this is the intended behaviour, but when setting a default asset value, when an asset field does not get provided a URL to import from, I was expecting the default asset to be assigned. This however does not appear to happen, but it might not be actually intended to use this way. I can use the "Use default value", but in most cases an asset URL is provided hence I don't want to do this.

### Steps to reproduce

1. Import to an asset field using a URL
2. Set a default asset value
3. When an asset URL value is not provided no fallback i.e. default value is used

### Additional info

- Craft version: 5.3.4
- PHP version: 8.3
- Database driver & version: MySQL
- Plugins & versions: Feed Me 6.2.1

**Comment by i-just** [comment]
Hi, I’m not sure if I understand you correctly, so please let me know if I missed your point.

I have just tested the following json feed
```
{
  "entries": [
    {
      "title": "asset1",
      "myAsset": "https://placehold.co/600x400.png"
    },
    {
      "title": "asset2",
      "myAsset": ""
    }
  ]
}
```
where the `assets` field is mapped to `myAsset` and a default is provided, like so:
<img width="1689" alt="Screenshot 2024-08-30 at 10 56 57" src="https://github.com/user-attachments/assets/2760b5b2-7330-4b65-b17b-fa82b6c52500">

With the above, the `asset2` entry gets the default asset assigned to it. However, if I remove `"myAsset": ""`, the default won’t be used. 

The above is expected behaviour. If the mapped key is not in the feed, then no value will be set for the field.

I hope this helps clarify things. I’ll close this now, but feel free to reply if I missed your point or if anything’s unclear.
