### ISSUE TITLE
Category not being related

### ISSUE THREAD

**Issue by justcookin** [engram-design/FeedMe#176]
I have an API endpoint that has a category field which is a basic comma delimited string -usually anywhere from 0-4 categories is the average. I am importing that into a Category field - trouble is if there are more than 1 category listed in the field it won't import it if I don't check the 'create new category' option. If I do it imports the whole string as a new category. So if I have 'Health Care' and 'Construction' as categories it won't relate to those existing categories but create a new one called "Health Care,Construction". Before 2.0.1 this wasn't an issue.

**Comment by engram-design** [comment]
Unfortunately, comma-delimited values aren't automatically parsed in as multiple values as they were in 1.0. This is due to the confusion where you might actually want a comma in your category title - but it will split into separate categories.

Are you able to edit the API endpoint at all? Your feed should be reformatted from:
```
{
  "categories": "Health Care,Construction"
}
```
to
```
{
  "categories": ["Health Care", "Construction"]
}
```

**Comment by justcookin** [comment]
Ah, makes sense. I was able to have the API changed and it worked fine - Thanks!
