### ISSUE TITLE
Userphotos, How to add them?

### ISSUE THREAD

**Issue by shornuk** [engram-design/FeedMe#187]
Hi, 

I've got the final thing I'm struggling with. Userphotos? Theres a field for them in the feed, but I cant quite work out how they should get imported. What do I need to be supplying that field?

I've tried a filename, (with the photos already in the userphotos folder) and tried a full url, but neither work. 

Thanks!

**Comment by engram-design** [comment]
Thanks for letting me know about this - thats all fixed in the [latest version](https://sgroup.com.au/plugins/feedme/download). Just ensure you place the image in the root of your `userphotos` folder, and Feed Me will take care of the rest. Supply just the filename.

Let me know if you have any issues!
