### ISSUE TITLE
Latest version breaks asset import - "There can't be more than one selection"

### ISSUE THREAD

**Issue by ldstevens** [engram-design/FeedMe#196]
I've returned to the depths of Content Import Hell™ where things _appeared_ to be going smoothly, but then I ran into a couple of demons.

Short story is that grabbing the latest Feed Me master resulted in a basic single-entry import (that was working prior) throwing the following error:

> News - Gallery test: {"entryImage":["There can\u2019t be more than one selection."]}

Here `entryImage` is set to get a single image uploaded from an external source, with "Keep Original" enabled, so might be a bug there? The assigned field has a single URL in the JSON export.

Long story is:
- Running mass import of 30k entries (most of which have an associated asset, and sometimes an asset gallery), broken up into 5k chunks.
- Noticed that I had bad URLs for some of the asset galleries, and 404 errors were (correctly) appearing in the logs.
- I re-ran a 5k chunk of entries after making the gallery assets available at the URLs that were 404ing.
- That import appears to have messed up some of the asset relations for the entries with galleries, as they then had wrong images associated with them (eek!) despite correct URLs in the import. I'm investigating this at the moment.
- I decided to see if Feed Me had been updated, and noticed the re-factor of image importing, which sounds great for not re-downloading assets when "keep original" is checked (especially when each 5k chunk takes 4-5 hrs to process!), so I thought I'd give that a go, but...
- I ran into the above error. I'm keen to give the refactored version a go to see if it corrects the messed up asset relations too, as I was getting occasional database locking errors in the logs when re-running the import, e.g.:

> 2017/04/11 09:11:46 [error] [plugin] [Forced] News - 0-5k: CDbCommand failed to execute the SQL statement: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction

... so not sure if that had anything to do with it. 🤔 

Hope that all makes some kind of vague sense 😅

**Comment by engram-design** [comment]
Try out the [latest version](https://sgroup.com.au/plugins/feedme/download) which should fix that issue. This can likely happen if there are two files that match before the upload process. This check is normally done for matching existing assets, but wasn't being done for uploaded assets, which are now extracted into a separate step in the import process.

If you're interested, a lot of the changes were around urls that aren't strictly provided as images, and instead dynamic. Think `http://mydomain.com/path/to/image`. Feed Me now looks at the contents of this url to determine the filetype. It also creates an md5 hash of the URL to create a seemingly random filename for this URL (because using `image.jpg` is a bit silly). In doing so, its able to check for existing assets that've been uploaded for this case too.

Regarding the deadlock error, this can sometimes happen if there are leftover things in the task, where its trying to edit an element at the same time something else is.

Let me know how that goes.

**Comment by ldstevens** [comment]
Awesome, thanks Josh, will give it a go 🙏 

Interesting about the md5 hashes too -- I was seeing them occasionally appear in the logs, and wondered where they were coming from.

**Comment by ldstevens** [comment]
"There can't be more than one selection" is fixed, thanks! 👍 

Will let you know what happens with wonky entry/asset relations.

**Comment by ldstevens** [comment]
Results of last night's mass import were... weird. Some entries had a different (incorrect) entry image associated with them, which is not what I was expecting. Not sure if errors during import are throwing out the relations or what, but I can't see any relation between the ID that is currently associated with an entry, and the ID that *should* be. It seems kind of random. I'm spending this afternoon trying to isolate the problem - haven't been able to reproduce locally, but trying a smaller import in my external dev host to see if I can reproduce there (that's where the issue has been occurring), and see if the images are being overwritten, or if the relation IDs are being changed.

**Comment by engram-design** [comment]
Closing, follow up issue in seperate issue.
