### ISSUE TITLE
matchExistingElement returning all products in for commerce product

### ISSUE THREAD

**Issue by danieltott** [engram-design/FeedMe#205]
Something is wrong with the elementCriteria for commerce products you've set up - if a Product doesn't exist, it is returning all of the products instead of an empty set, so it keeps just updating the first product. I can't run this feed more than once. It works the first time since there are no products anyway, but after that it just tries to update the same product over and over again even though they all have different SKUs.

The function matchExistingElement in Commerce_ProductFeedMeElementType.php is returning ALL of the products, even though there's no match in sku. This might actually be the problem i was having in #204 - I'm not quite sure about that since I've found this new problem.

**Comment by engram-design** [comment]
This should be fixed in the [latest master](https://sgroup.com.au/plugins/feedme/download), and thanks also for the PR.

Additionally, I've removed all variant attributes from being able to be set as a unique identifier - this includes the variant Title. While this would be nice, the Variant Element itself doesn't support this as a criteria, so it simply won't work. If you tried to match against a variant's title, it'd return all variants, which is certainly not what we want.

Please let me know if you continue to have issues!
