### ISSUE TITLE
Issue with OSes that are cap insensitive

### ISSUE THREAD

**Issue by mildlygeeky** [engram-design/FeedMe#32]
Quick quasi-issue for people who upgraded from pre-1.4.0 versions. We found we were getting 404 errors in the console that the CSS and JS files for FeedMe weren't being found in the latest versions after upgrading from pre-1.4.0.

We found that the changed from the CSS and JS files in v. 1.4.0 from "feedme.css" to "FeedMe.css", for example, did not get picked up on in git, likely because Mac OS X if capitalization-insensitive.

Perhaps consider going back to the code looking for all-lowercase resources, and putting the CSS and JS back to the way they were in case there are others having the same issues?

**Comment by engram-design** [comment]
Thanks for posting this - for future benefit, check out the [release notes](https://github.com/engram-design/FeedMe#release-notes). In hindsight, I really wish I'd considered this case, as a few people have had issues with this in the past.

**Comment by neekster** [comment]
I've run into this issue many times in the past. It's actually more of a Git configuration issue really. I update the config for all my repos have:

`ignorecase = false`

We never had this problem since in many years, first thing I do every time I create a repo is to change that setting, one of these days I'll check if I can make it default.

**Comment by engram-design** [comment]
Closing for now - if people haven't updated by now, too bad!
