### ISSUE TITLE
Feed me updates all entries even tho there is nothing to update.

### ISSUE THREAD

**Issue by stigzelm** [engram-design/FeedMe#403]
### Description

When creating a feed that will import around 1000 entries. I expect feed-me not to update entries and categories if there is nothing to update.

I have a json file witch gets updated X amount of times a day. The json file contains around 1000 entries that will get mapped and created as entries in craft. Would it not be correct to check if the entry is matching the json item and if nothing has changed the feed will not do anything.

Now when I run the import, the log says that all entries are updating and it takes around 15 minutes.

### Steps to reproduce

1. Create a json file with around 100 items.
2. Create a feed and map it with all types of fields (plain text, category, number, table, matrix....etc.)
3. Run the feed the first time, this is understandable that it takes longer.
4. Run the feed again from the same json file with the same data. This should take seconds because nothing has changed. So no entries should update.

### Additional info

- Plugin version: 3.0.0-beta.21
- Craft version: Pro 3.0.23.1

**Comment by engram-design** [comment]
Feed Me is semi-smart at deciding if it should update elements (entries), however I'm afraid it'll always update an element, regardless of wether its data has changed or not.

The reason for this is complicated due to field content, relational element fields, Matrix, third-party fields and more. It's difficult to say compare related categories to the content in your feed - that's just one example.

It does help with speed to enable the `checkExistingFieldData` [config option](https://verbb.io/craft-plugins/feed-me/docs/get-started/configuration), but won't skip the entry entirely.

By the way, some sort of intelligent 'hashing' of an entire element is definitely on the roadmap to prevent such massive amounts of unnecessary updating. In fact, everything else in Feed Me is exceptionally quick, and the bottleneck is the element-saving mechanism handled by Craft. Like I said - understand the frustration, and its high on our priority.
