### ISSUE TITLE
PHP notice Undefined offset: 0 Error when creating a feed

### ISSUE THREAD

**Issue by theswebsite** [engram-design/FeedMe#51]
Hi,

I'm getting the following error when I try and create a new XML or JSON feed.

```
PHP notice
Undefined offset: 0 
```

I'm really not sure my feeds are in a proper format. Is it possible to see an example XML or JSON feed that works with the plugin please?

Thanks

**Comment by engram-design** [comment]
Hi there - this is likely due to not specifying the Primary Element field correctly. For reference, it should be the repeating node containing your information.

For instance, you might have:

```
<videos>
    <video>
        <title>My Title</title>
    </video>    
    <video>
        <title>Another Title</title>
    </video>    
</videos>
```

In which case, the primary element would be `video`.

Having said that, the latest master should fix all that!

**Comment by theswebsite** [comment]
Thanks for the reply, and you were indeed correct. It was my data that was causing the issue.

**Comment by engram-design** [comment]
No worries - its a little confusing at the moment. Will be putting together full examples with walkthrough soon for XML and JSON!
