### ISSUE TITLE
Have category data but plugin ignores it

### ISSUE THREAD

**Issue by subratom** [engram-design/FeedMe#61]
I have a list of items under a heading and when I use the plugin using JSON format, the data is as follows

category : "Category Header/ Sub Category"

I have noticed that the plugin is creating a category name "Category Header/ Sub Category" rather than man the item.

Am I using the wrong format? or Is something off when the data is being imported. 

P.S. : Many thanks for this plugin and prompt answers.

**Comment by engram-design** [comment]
Categories are created automatically if they don't already exist. If they do exist, it should map the existing category to the entry. Are you trying to map to a sub-category? If so, you'd just provide the sub-category Title. Creating sub-categories is currently not supported though, and it would create this category at the top level.

Hope that makes sense - but let me know if thats missing what the issue is!

**Comment by subratom** [comment]
I did try that but that information wasn't imported. When I saw the data was "Category/Sub Category" and saw how the plugin was creating more categories, I changed one of them to just "Subcategory" and the item had no category information

**Comment by engram-design** [comment]
Any luck with this one?

**Comment by subratom** [comment]
Yes the data is being imported. I had to change it to direct subcategory name rather than trying to pass parent category followed by child category.
