### ISSUE TITLE
Access attribute in primary element

### ISSUE THREAD

**Issue by style4** [engram-design/FeedMe#86]
Is it:
- possible to use the id (see below) in "Check for duplicate"? 
- possible to read DetailUrl from a template?

`<Items><Item Id="1" DetailUrl="http://...">...</Item></Items>`

**Comment by engram-design** [comment]
Currently, you can't use attributes in the control-panel side of things, so that rules out using it to check for duplicates I'm afraid.

However, you can use attributes in your templates. Refer to here - https://github.com/engram-design/FeedMe#template-example or in your case: `{{ xml.field.attributes.detailurl }}`

**Comment by engram-design** [comment]
Attribute access has been added in [Feed Me 2](http://sgroup.com.au/plugins/feedme).
